development:
  adapter: postgresql
  database: openbank
  username: michael
  password: 
  host: localhost

test:
  adapter: postgresql
  database: openbank
  username: michael
  password: 
  host: localhost

production:
  adapter: postgresql
  database: openbank
  username: michael
  password: 
  host: localhost
